apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
  - image: hello-world
deploy:
  kubectl:
    manifests:
      - k8s.yml
portForward:
  - resourceType: service
    resourceName: hello-world
    port: 8080
    localPort: 8080
